package com.notiflogger.app;

// Объединённый файл всех Java классов приложения

// ... ActivationManager ...
// ... LogsActivity ...
// ... LogsAdapter ...
// ... MainActivity ...
// ... NotificationLoggerService ...
// ... PermissionsActivity ...
// ... SettingsActivity ...
// ... Utils ...

// Весь код из ActivationManager.java
// ...existing code...

// Весь код из LogsActivity.java
// ...existing code...

// Весь код из LogsAdapter.java
// ...existing code...

// Весь код из MainActivity.java
// ...existing code...

// Весь код из NotificationLoggerService.java
// ...existing code...

// Весь код из PermissionsActivity.java
// ...existing code...

// Весь код из SettingsActivity.java
// ...existing code...

// Весь код из Utils.java
// ...existing code...
